version: '3.6'
services:
  db:
    image: postgres:12.4-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=mysecretpassword
      - PGDATA=/var/lib/postgresql/data/pgdata
    restart: always
    networks:
      - voucher_network
  dbseed:
    depends_on:
      - db
      - dbmigrate
    image: golang:1.16.0
    volumes:
      - .:/go/src/voucher_service
    working_dir: /go/src/voucher_service
    command: go run cmd/seed/main.go
    networks:
      - voucher_network
  go:
    depends_on:
      - db
      - dbmigrate
      - dbseed
    image: golang:1.16.0
    ports:
      - "5000:5000"
    volumes:
      - .:/go/src/voucher_service
    working_dir: /go/src/voucher_service
    command: go run cmd/main.go
    networks:
      - voucher_network
  dbmigrate:
    image: "choonkeat/dbmigrate"
    environment:
      - DATABASE_URL=postgres://user:mysecretpassword@db:5432/postgres?sslmode=disable
      - DATABASE_DRIVER=postgres
    volumes:
      - .:/migrations
    working_dir: /migrations
    command: ${DBMIGRATE_CMD:--up -server-ready 60s -create-db}
    depends_on:
        - db
    networks:
      - voucher_network
  dbmigratetest:
    image: "choonkeat/dbmigrate"
    environment:
      - DATABASE_URL=postgres://user:mysecretpassword@db:5432/postgres_test?sslmode=disable
      - DATABASE_DRIVER=postgres
    volumes:
      - .:/migrations
    working_dir: /migrations
    command: ${DBMIGRATE_CMD:--up -server-ready 60s -create-db}
    depends_on:
        - db
    networks:
      - voucher_network
  gotest:
    depends_on:
      - db
      - dbmigratetest
    image: golang:1.16.0
    volumes:
      - .:/go/src/voucher_service
    working_dir: /go/src/voucher_service
    command: env CGO_ENABLED=0 go test ./...
    networks:
      - voucher_network
volumes:
  db_data:
networks:
  voucher_network:
    name: voucher_network
